### ISSUE TITLE
client render doesn't work

### ISSUE THREAD

**Issue by arkist** [Pitzcarraldo/reduxible-example#7]
client render was not working correctly.
styles don't show, HMR not works, links passing a request to server-side.

it seems reduxible's `render` method got a problem.
I play with react-router & redux-simple-router v2.x on my project but Reduxible is based on v1 currently, so It is hard to figure out how to fix it. 

Has any idea?

**Comment by pitzcarraldo** [comment]
The redux-simple-router v2.x broke the backward compatibility.
Many APIs were changed. But reduxible has peerDependency with v1.x.
So it can't be run with redux-simple-router v2.x.
And I'm observing updates of redux-simple-router.
It is updating almost every day now.
So I'll apply v2.x to reduxible when after few weeks.

**Comment by arkist** [comment]
@Pitzcarraldo No, I mean error occurs on 1.x but My knowledge is on to 2.x so I didn't figure out how to fix it. 
checkout project cleary and test please.

**Comment by pitzcarraldo** [comment]
I've removed `node_modules` and re-run `npm install`.
And `npm run dev` is works well for me.
Tell me how did you run the application.

**Comment by pitzcarraldo** [comment]
:warning: **Caution**
I've renamed reducer and middleware to reducers and middlewares that default options of the reduxible instance. Plz check that point. Sorry, I modified it but didn't edit readme.

**Comment by arkist** [comment]
Sorry, I checked wrong port. 
log: `server listening at http://:::3000` is confusing me. `:8080` looks good.
